version: "3.7"

services:
  #app:
  #  build: ./
  #  volumes:
  #    - ./:/usr/src/app
  #  ports:
  #    - "8000:8000"
  #  networks:
  #    - examplenetwork
  ### PostgreSQL Server Container ##################################
  postgres:
    build: ./.docker/postgres
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword

volumes:
  db-postgres:
